In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import keras

%matplotlib inline

Using TensorFlow backend.


In [2]:
from keras.models import Sequential
from keras.layers import Dense

In [3]:
dataset = pd.read_csv('Churn_modelling.csv')

In [4]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
#IMPORTING THE DATASET
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [6]:
#ENCODING THE CATEGORCAL DATA
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder() #WE WILL ENCODE TWO FEATURES
X[:,1] = labelencoder_X_1.fit_transform(X[:, 1])

In [7]:
labelencoder_X_2 = LabelEncoder() 
X[:,2] = labelencoder_X_2.fit_transform(X[:, 2])

In [8]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
# BECAUSE ANY COUNTRY IS NOT HIGHER IN THE RANK, WE NEED TO
#CREATE DUMMY VARIABLES TO ESCAPE THE DUMMY VARIABLE TRAP.
#NO NEED TO IT FOR GENDER BECAUSE IT IS ONLY TWO CATEGORIES

onehotencoder = OneHotEncoder(categorical_features=[1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\Pc\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Pc\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
X = X[:, 1:] # WE CUT TH FIRST DUMMY VAR. TO AVOID THE TRAP

In [11]:
# SPLITTING THE DATASET INTO TRAINING AND TEST SET
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [12]:
#FEATURE SCALING- IT IS IMPORTANT TO DO IN ANN BECAUSE IT IS A 
#COMPLEX ALGORITHM
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
#INITIALIZE ANN
classifier = Sequential()

In [14]:
#ADDING THE INPUT LAYER AND FIRST LAYER
#INPUT LAYER= OUR FEATURES,OUTPUT LAYER= Y COLUMN
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

In [15]:
#ADDING THE SECOND LAYER
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

In [16]:
#ADDING THE OUTPUT LAYER
# IF WE HAVE MORE THAN 2 CATEGORIES, CHOOSE SUPERMAX AS ACTIVATION
#AND NU OF CATEGORIES AS UNITS
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [17]:
#COMPILINg THE ANN(STOCH. GRAD.DESC.)
#optimizer : GRAd.Desc. model
#loss: loss funct-- binary_crossentropy or categorical_crossentropy
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics = ['accuracy'] )

In [18]:
#FITTING THE ANN TO TRAINING SET
classifier.fit(X_train,y_train, batch_size=10, nb_epoch=25 )

C:\Users\Pc\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Epoch 1/25
8000/8000 [==============================] - 2s 226us/step - loss: 0.4815 - acc: 0.7960
Epoch 2/25
8000/8000 [==============================] - 1s 112us/step - loss: 0.4264 - acc: 0.7960
Epoch 3/25
8000/8000 [==============================] - 1s 106us/step - loss: 0.4183 - acc: 0.8242
Epoch 4/25
8000/8000 [==============================] - 1s 108us/step - loss: 0.4123 - acc: 0.8307
Epoch 5/25
8000/8000 [==============================] - 1s 115us/step - loss: 0.4081 - acc: 0.8327
Epoch 6/25
8000/8000 [==============================] - 1s 160us/step - loss: 0.4060 - acc: 0.8340
Epoch 7/25
8000/8000 [==============================] - 1s 132us/step - loss: 0.4035 - acc: 0.8345
Epoch 8/25
8000/8000 [==============================] - 1s 111us/step - loss: 0.4025 - acc: 0.8331
Epoch 9/25
8000/8000 [==============================] - 1s 110us/step - loss: 0.4013 - acc: 0.8370
Epoch 10/25
8000/8000 [==============================] - 1s 121us/step - loss: 0.3996 - acc: 0.8362
Epoch 11/

In [19]:
y_pred = classifier.predict(X_test)

In [20]:
y_pred

array([[0.16449864],
       [0.29418996],
       [0.11698656],
       ...,
       [0.17690386],
       [0.13737406],
       [0.12430664]], dtype=float32)

In [22]:
# WE NEED TRUES OR FALSES TO USE IN CONFUSION MATRIX 
#SO WE NEED TO CONVERT ARRAY TO BOOLEANS
y_pred = (y_pred>0.5)

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [24]:
cm

array([[1550,   45],
       [ 271,  134]], dtype=int64)

In [25]:
(1550+134)/2000

0.842